### ISSUE TITLE
MPES: Remove `_` from `beam_TYPE` and `source_TYPE`

### ISSUE THREAD

**Issue by lukaspie** [FAIRmat-NFDI/nexus_definitions#165]
Ideally, it would be nice to keep the `_` and also just allow `beam(NXbeam)` if you only have one. But, this is probably not possible with NeXus.

**Comment by mkuehbach** [comment]
The question is can "_" be added to the list of UPPERCASE characters for concepts of nameType={"partial" | "any"}, currently this is not possible, I even heard from @benajamin that the notation source_TYPE is the suggested way to do so, but identifierNAME was accepted in NXobject after the Autumn Code Camp.

**Comment by mkuehbach** [comment]
Indeed "Sometimes it is necessary to combine words in order to build a descriptive name for a field or a group. In such cases lowercase words are connected by underscores." https://manual.nexusformat.org/datarules.html, no statement that separating different instances are excluded from this best practice.

**Comment by mkuehbach** [comment]
That mirrors my understanding, in fact I also see value in that people are not forced to write beam_1 when beam1 is likewise generating a disjoint label for distinguishing instances. I think @benajamin's thought is that the documentation is clear enough and I think it is good the way it is like this.
